### ISSUE TITLE
Backup / Restore Option for OME 

### ISSUE THREAD

**Issue by SmrtAss** [dell/OpenManage-Enterprise#154]
Currently there is no ability to backup and restore ALL Settings for a OME for the event of a loss of system OR a planned migration from one system to another (think botched upgrade corrupted system).  We would like an ability to backup and restore all settings, templates, discoveries, configurations, etc...  from one OME to another.

**Comment by grantcurell** [comment]
This one is not possible or I suppose to split semantic hairs - not feasible. Nothing is impossible given enough time 😂

That said, if you want to back up a VM from an enterprise standpoint you could run something like IDPA. Or if you want to keep it super simple and free, I'd recommend just using a script that runs [OVF Tool](https://code.vmware.com/web/tool/4.4.0/ovf) using `ovftool.exe vi://<vcenter-name>/<datacenter_name>/vm/vm-name  <Folder path to save the OVA file\ova-name.ova>`.

You can run it as a scheduled task and it makes for a pretty clean backup. You could have it pull an image of the VM weekly.

Since I can't don't this with the API I'm closing the ticket, but feel free to respond here or shoot me an e-mail.
